from pyspark.sql.types import *

# Schema for gps dataset
gps_schema = StructType([
  StructField('LATITUDE', DoubleType(), False),
  StructField('LONGITUDE', DoubleType(), False),
  StructField('SPEED', FloatType(), False),
  StructField('LOCAL DATETIME', TimestampType(), False),
  StructField('VALID', StringType(), True),
  StructField('UTC DATETIME', TimestampType(), False),
  StructField('ID', StringType(), False),
  StructField('fclass', StringType(), True),
  StructField('name', StringType(), True),
  StructField('index_right', StringType(), False),
  StructField('distance_to_road', DoubleType(), False),
])

# Schema of trips
trips_schema = StructType([
  StructField("KEY", StringType(), False),
  StructField("ID", StringType(), False),
  StructField("Day_EMG", StringType(), False),
  StructField("Date_EMG", DateType(), False),
  StructField("Day_Type", StringType(), False),
  StructField("ID_Trip_Days", IntegerType(), False),
  StructField("Type_Trip_OD", StringType(), False),
  StructField("Code_INSEE_O", StringType(), False),
  StructField("Code_INSEE_D", StringType(), False),
  StructField("Zone_O", StringType(), False),
  StructField("Zone_D", StringType(), False),
  StructField("Time_O", StringType(), False),
  StructField("Time_D", StringType(), False),
  StructField("Duration", FloatType(), False),
  StructField("Purpose_O", StringType(), False),
  StructField("Purpose_D", StringType(), False),
  StructField("Main_Mode", StringType(), False),
  StructField("Weight_Day", DoubleType(), False),
  StructField("Day_EMG_encoded", IntegerType(), False),
  StructField("Date_EMG_encoded", IntegerType(), False),
  StructField("Day_Type_encoded", IntegerType(), False),
  StructField("Type_Trip_OD_encoded", IntegerType(), False),
  StructField("Zone_O_encoded", IntegerType(), False),
  StructField("Zone_D _encoded", IntegerType(), False),
  StructField("Purpose_O_encoded", IntegerType(), False),
  StructField("Purpose_D_encoded", IntegerType(), False),
  StructField("Main_Mode_encoded", IntegerType(), False),
  StructField("Time_O_Hour", IntegerType(), False),
  StructField("Time_D_Hour", IntegerType(), False),
  StructField("Time_O_sin", DoubleType(), False),
  StructField("Time_O_cos", DoubleType(), False),
  StructField("Time_D_sin", DoubleType(), False),
  StructField("Time_D_cos", DoubleType(), False),
])

weather_schema = StructType([
  StructField("time_utc", TimestampType(), False),
  StructField("icao", StringType(), False),
  StructField("name", StringType(), False),
  StructField("latitude", DoubleType(), False),
  StructField("longitude", DoubleType(), False),
  StructField("temp", FloatType(), False),
  StructField("rhum", FloatType(), False),
  StructField("prcp", FloatType(), False),
  StructField("dwpt", FloatType(), False),
  StructField("pres", FloatType(), False),
  StructField("wspd", FloatType(), False),
  StructField("wdir", FloatType(), False),
])

individuals_schema = StructType([
  StructField("ID", StringType(), False),
  StructField("CODGEO", StringType(), False),
  StructField("AREA_NAME", StringType(), False),
  StructField("SEX", StringType(), False),
  StructField("AGE", IntegerType(), False),
  StructField("DIPLOMA", StringType(), False),
  StructField("PRO_CAT", IntegerType(), False),
  StructField("TYPE_HOUSE", StringType(), False),
  StructField("NBPERS_HOUSE", IntegerType(), False),
  StructField("NB_10", FloatType(), False),
  StructField("NB_11_17", FloatType(), False),
  StructField("NB_18_24", FloatType(), False),
  StructField("NB_25_64", FloatType(), False),
  StructField("NB_65", FloatType(), False),
  StructField("PMR", FloatType(), False),
  StructField("DRIVING_LICENCE", IntegerType(), False),
  StructField("NB_CAR", IntegerType(), False),
  StructField("TWO_WHEELER", IntegerType(), False),
  StructField("BIKE", IntegerType(), False),
  StructField("ELECT_SCOOTER", IntegerType(), False),
  StructField("NAVIGO_SUB", IntegerType(), False),
  StructField("IMAGINER_SUB", IntegerType(), False),
  StructField("OTHER_SUB_PT", IntegerType(), False),
  StructField("BIKE_SUB", IntegerType(), False),
  StructField("NSM_SUB", IntegerType(), False),
  StructField("WEIGHT_INDIV", DoubleType(), False),
  StructField("GPS_RECORD", IntegerType(), False),
  StructField("sex_encoded", DoubleType(), False),
  StructField("WEIGHT_INDIV_normalized", DoubleType(), False),
  StructField("diploma_encoded", DoubleType(), False),
  StructField("type_house_encoded", DoubleType(), False),
])